spring.application.name=springain-mcp-client

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:8b

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.initialized=true
spring.ai.mcp.client.request-timeout=6000s

spring.ai.mcp.client.streamable-http.connections.weather-server.url=http://localhost:8081/mcp